# Generated by Django 5.2.6 on 2025-09-11 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='Stanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipologia', models.CharField(choices=[('SING', 'Singola'), ('MATR', 'Matrimoniale'), ('DOPP', 'Doppia con Letti Singoli'), ('TRIP', 'Tripla'), ('SUIT', 'Suite')], default='MATR', max_length=4)),
                ('ospiti_massimo', models.IntegerField()),
                ('ha_problemi', models.BooleanField(default=False)),
                ('descrizione_problema', models.TextField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stanze', to='gestione_hotel.hotel')),
            ],
            options={
                'verbose_name': 'Stanza',
                'verbose_name_plural': 'Stanze',
            },
        ),
    ]
