# Generated by Django 5.2.6 on 2025-09-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stanza',
            name='descrizione_problema',
            field=models.TextField(blank=True, null=True),
        ),
    ]
