# Generated by Django 5.2.6 on 2025-09-11 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Hotel', 'verbose_name_plural': 'Hotel'},
        ),
        migrations.AddField(
            model_name='hotel',
            name='stato',
            field=models.CharField(choices=[('ATTIVO', 'Attivo'), ('CHIUSO', 'Chiuso'), ('ARCHIVIATO', 'Archiviato')], default='ATTIVO', max_length=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stanza',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stanze', to='gestione_hotel.hotel'),
        ),
    ]
