# Generated by Django 5.2.6 on 2025-09-13 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestione_hotel', '0002_alter_hotel_options_hotel_stato_alter_hotel_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
            },
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_check_in', models.DateField()),
                ('data_check_out', models.DateField()),
                ('stato', models.CharField(choices=[('CONFERMATA', 'Confermata'), ('CANCELLATA', 'Cancellata'), ('COMPLETATA', 'Completata')], default='CONFERMATA', max_length=10)),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('modificata_il', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='booking.cliente')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='gestione_hotel.hotel')),
                ('stanza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='gestione_hotel.stanza')),
            ],
            options={
                'verbose_name': 'Prenotazione',
                'verbose_name_plural': 'Prenotazioni',
                'ordering': ['-data_check_in'],
            },
        ),
    ]
